# Generated by Django 2.1.15 on 2024-01-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Товары',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('supplier_company', models.CharField(max_length=100)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('taste', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
            ],
        ),
    ]
