# Generated by Django 2.1.15 on 2024-01-04 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineshop', '0002_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сотрудники',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('имя', models.CharField(max_length=50)),
                ('фамилия', models.CharField(max_length=50)),
                ('стаж_работы', models.PositiveIntegerField()),
                ('должность', models.CharField(max_length=100)),
                ('телефон', models.CharField(max_length=15)),
                ('почта', models.EmailField(max_length=254)),
                ('место_жительства', models.CharField(max_length=100)),
                ('любимое_вино', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wineshop.Товары')),
            ],
        ),
    ]
