# Generated by Django 2.1.15 on 2024-01-05 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineshop', '0003_сотрудники'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee_images/')),
                ('сотрудник', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wineshop.Сотрудники')),
            ],
        ),
    ]
