# Generated by Django 2.1.15 on 2024-01-05 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wineshop', '0004_imagedev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Заказ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('общая_стоимость', models.DecimalField(decimal_places=2, max_digits=10)),
                ('имя', models.CharField(max_length=50)),
                ('фамилия', models.CharField(max_length=50)),
                ('номер_телефона', models.CharField(max_length=15)),
                ('оплачен', models.BooleanField(default=False)),
                ('пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Корзина',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.PositiveIntegerField(default=1)),
                ('заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineshop.Заказ')),
                ('пользователь', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineshop.Товары')),
            ],
        ),
        migrations.AddField(
            model_name='заказ',
            name='товары',
            field=models.ManyToManyField(through='wineshop.Корзина', to='wineshop.Товары'),
        ),
    ]
