# Generated by Django 2.1.15 on 2024-01-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wineshop', '0006_auto_20240105_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ОформленныйЗаказ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_заказа', models.DateTimeField(auto_now_add=True)),
                ('оплачен', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ТоварВЗаказе',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('количество', models.IntegerField(default=0)),
                ('заказ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='товары_в_заказе', to='wineshop.ОформленныйЗаказ')),
                ('товар', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wineshop.Товары')),
            ],
        ),
    ]
