# Generated by Django 2.1.15 on 2024-01-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wineshop', '0008_отзыв'),
    ]

    operations = [
        migrations.CreateModel(
            name='Поставщики',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('image', models.ImageField(upload_to='supplier_images/', verbose_name='Изображение')),
            ],
        ),
        migrations.AlterField(
            model_name='отзыв',
            name='товар',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='отзывы', to='wineshop.Товары'),
        ),
    ]
