# Generated by Django 2.1.15 on 2024-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wineshop', '0009_auto_20240106_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Клиенты',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название_компании', models.CharField(blank=True, max_length=255, null=True)),
                ('имя', models.CharField(max_length=100)),
                ('фамилия', models.CharField(max_length=100)),
                ('контакты', models.CharField(blank=True, max_length=255, null=True)),
                ('картинка', models.ImageField(blank=True, null=True, upload_to='client_images/')),
                ('отзыв', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
